stages:
    - build-frontend
    - build-backend
build-frontend:latest:
    stage: build-frontend
    when: on_success
    only:
      - master
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -f "frontend/Dockerfile" -t $CI_REGISTRY/$CI_PROJECT_PATH/frontend:latest ./frontend
      - docker push $CI_REGISTRY/$CI_PROJECT_PATH/frontend:latest
build-backend:latest:
    stage: build-backend
    when: on_success
    only:
      - master
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -f "backend/Dockerfile" -t $CI_REGISTRY/$CI_PROJECT_PATH/backend:latest ./backend
      - docker push $CI_REGISTRY/$CI_PROJECT_PATH/backend:latest