version: "3.7"
services:
  db:
    image: arangodb/arangodb
    ports: 
        - 8529:8529
    environment: 
        - ARANGO_ROOT_PASSWORD=
  # Angular frontend project deployed on nginx.
  frontend:
    image: cc-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - ${FRONTEND_PORT}:80
  