version: "3.7"
services:
  cc_backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: registry.gitlab.com/yikaiyang/codecity/backend:latest
    ports:
      - 3000:3000
    environment:
      GIT_PROJECTS_FOLDER: /projects
    volumes:
      - "./:/projects"
  cc_frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image:  registry.gitlab.com/yikaiyang/codecity/frontend:latest
    ports:
      - 80:80
