version: "3.7"
services:
  # Connection string: mongodb://root:example@localhost:27017
  cc-mongodb:
    container_name: cc-mongodb
    image: mongo
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  cc-backend:
    container_name: cc-backend
    image: codecity-backend:latest
    ports: 
        - 3000:3000
    volumes: 
        - '/Users/yikaiyang/Projects/BA2/projects/ue2_github/:/.git'
  cc-frontend:
    image: cc-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - ${FRONTEND_PORT}:80
  