version: "3.7"
services:
  cc-backend:
    container_name: cc-backend
    image: codecity-backend:latest
    ports: 
        - 3000:3000
    volumes: 
        - '/Users/yikaiyang/Projects/BA2/projects/ue2_github/:/.git'
  # frontend:
  #   image: cc-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - ${FRONTEND_PORT}:80
  